### ISSUE TITLE
Provide compiled executable

### ISSUE THREAD

**Issue by petrroll** [MahdiSafsafi/ImmersiveColors#1]
Compiled executable would be very useful for browsing different accent colors and their respective names.

//I know I can compile it myself, it would just be a bit more convenient to have it already done as a release.

**Comment by MahdiSafsafi** [comment]
Here is a compiled demo for you : 
[Immersive_Color_Demo.zip](https://dl.dropboxusercontent.com/u/99625333/Immersive_Color_Demo.zip)
